{
 "title": "Loki Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "总日志速率",
   "type": "timeseries",
   "description": "记录5分钟内普通日志与错误日志趋势",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({job=\"varlogs\"}[5m]))"
    },
    {
     "expr": "sum(rate({job=\"varlogs\"} |~ \"(?i)error\" != \"query=\" != \"caller=engine.go\" != \"caller=metrics.go\" [5m]))"
    }
   ]
  },
  {
   "title": "各文件日志量",
   "type": "bargauge",
   "description": "过去 5 分钟内，平均每秒产生多少条日志。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (filename) (rate({job=\"varlogs\"}[5m]))"
    }
   ]
  },
  {
   "title": "原始错误日志",
   "type": "logs",
   "description": "实时错误日志详情",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |~ \"(?i)error\" != \"caller=\" != \"query=\""
    }
   ]
  },
  {
   "title": "24小时错误总数\t",
   "type": "stat",
   "description": "近24小时累计错误日志条数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"varlogs\"} |~ \"(?i)error\" != \"caller=\" != \"query=\" [24h]))"
    }
   ]
  }
 ]
}